### PR TITLE
fix: allow different shops to have same tag name

### LINKED ISSUE #28: It's impossible to create tags with same names in different shops
Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues](https://github.com/reactioncommerce/reaction/issues)

## Issue Description
The problem is that Tag's slug is unique across the whole system. For system where there can be multiple shops it doesn't look like a good solution since it's a very common case to have same tags in different shops

## Steps to Reproduce

1.  Start Reaction Development Platform
2. Log in to reaction-admin
3. Create a shop
4. Create a tag with name 'food'
5. Create one more shop
6. Create a tag with name 'food' in new shop

Expected result: Tag 'food' can be created since there are no more tags with name 'food' in this shop
Received result: Tag 'food' can't be created because of error `GraphQL error: Slug food is already in use `

## Possible Solution
a) Slugs can be unique per shop.
b) Automatic slug resolution when there are duplicates like the one made for products (as I can see it doesn't throw but generate a new unique slug)

### Versions
Reaction: 3.10.0

Thanks in advance!

### PR DESCRIPTION
**Pull request by MohanNarayana**
Signed-off-by: Mohan Narayana <mohan.narayana@mailchimp.com>

Resolves #28 
Impact: **minor**
Type: **bugfix**

## Issue
The problem is that Tag's slug is unique across the whole system. For system where there can be multiple shops it doesn't look like a good solution since it's a very common case to have same tags in different shops

## Solution
Make slug and shopId index pair value to be unique.

## Testing
1. Set up api-migrations using [these](https://github.com/reactioncommerce/api-migrations#local-development-usage) steps. NOTE: Use node 14 at step 3. Copy the new api-plugin-tags to api-migrations/node_modules/@reactioncommerce.
2. Add below code to api-migrations/migrator.config.js
    `{
      namespace: "tags",
      package: "@reactioncommerce/api-plugin-tags",
      version: 2
    }`
3. Run `MONGO_URL=mongodb://localhost:27017/reaction npx migrator migrate`
4. Check DB for index 'slug_1' in the tags table.

### CODE REVIEW

File: migrations/2.js [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+    progress(0);
+
+    const index = "slug_1";
+    await db.collection("Tags").dropIndex(index);
+
+    progress(100);
+}
+
+export default {
+    down: "unnecessary",
```
Comment (delagroove) [inline migrations/2.js]: isn't 'down' the re-creation of the dropped index?
it makes that is deemed unnecessary but just wanted to make sure.

**Review by delagroove — APPROVED** [review]
